import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderMcpInstructions } from '../../manifest-agent-content/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'src', 'generated', 'instructions.ts');
const text = `// Generated by scripts/generate-content.mjs. Do not edit manually.
export const MANIFEST_INSTRUCTIONS = ${JSON.stringify(renderMcpInstructions())} as const;
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, text);
